In [62]:
import numpy as np
import tensorflow as tf

In [64]:
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=np.float32)

y = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [65]:
w1 = tf.Variable(np.array([[5, -7],
                           [5, -10]], dtype=np.float32))

w2 = tf.Variable(np.array([[3, -3],
                           [4, -21]], dtype=np.float32))

w3 = tf.Variable(np.array([[1], [-3]], dtype=np.float32))

b1 = tf.Variable(np.array([-8, 3], dtype=np.float32))
b2 = tf.Variable(np.array([-2, 4], dtype=np.float32))
b3 = tf.Variable(np.array([-1], dtype=np.float32))

In [43]:
linear_output1 = tf.matmul(X, w1) + b1

In [46]:
linear_output1

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ -8.,   3.],
       [ -3.,  -7.],
       [ -3.,  -4.],
       [  2., -14.]], dtype=float32)>

In [48]:
activation1 = tf.sigmoid(linear_output1)
activation1

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[3.3535014e-04, 9.5257413e-01],
       [4.7425874e-02, 9.1105117e-04],
       [4.7425874e-02, 1.7986210e-02],
       [8.8079703e-01, 8.3152798e-07]], dtype=float32)>

In [50]:
linear_output2 = tf.matmul(activation1, w2) + b2
linear_output2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[  1.8115532, -16.006376 ],
       [ -1.8540821,   3.838591 ],
       [ -1.7857666,   3.4799347],
       [  0.6425812,   1.3574045]], dtype=float32)>

In [51]:
activation2 = tf.sigmoid(linear_output2)
activation2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[8.5954946e-01, 1.1181989e-07],
       [1.3539432e-01, 9.7892958e-01],
       [1.4359254e-01, 9.7011143e-01],
       [6.5533668e-01, 7.9533756e-01]], dtype=float32)>

In [58]:
linear_output3 = tf.matmul(activation2, w3) + b3
linear_output3

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.1404509],
       [-3.8013945],
       [-3.7667418],
       [-2.730676 ]], dtype=float32)>

In [59]:
y_pred = tf.sigmoid(linear_output3)


In [60]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
optimizer = tf.keras.optimizers.Adam()

In [69]:
# 훈련 과정
epochs = 1000
for epoch in range(epochs):
    with tf.GradientTape() as tape:
        # 순전파
        linear_output1 = tf.matmul(X, w1) + b1
        activation1 = tf.sigmoid(linear_output1)
        linear_output2 = tf.matmul(activation1, w2) + b2
        activation2 = tf.sigmoid(linear_output2)
        linear_output3 = tf.matmul(activation2, w3) + b3
        y_pred = tf.sigmoid(linear_output3)
        
        # 손실 계산
        loss = loss_fn(y, y_pred)
        
    # 그래디언트 계산 및 역전파
    gradients = tape.gradient(loss, [w1, w2, w3, b1, b2, b3])
    print("\n gradients : ",gradients)
    optimizer.apply_gradients(zip(gradients, [w1, w2, w3, b1, b2, b3]))
    
    # 로그 출력
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss.numpy()}")


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00730155, -0.0025301 ],
       [-0.007107  , -0.04124928]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00593941, -0.01858799],
       [ 0.03872678,  0.00219383]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01601512],
       [ 0.04607097]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01387668, -0.04394685], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03305598, -0.01609313], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.03928412], dtype=float32)>]
Epoch 0, Loss: 0.49430206418037415

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00726351, -0.00251102],
       [-0.00709185, -0.04115772]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00592226, -0.01859729],
       [ 0.0387683 ,  0.00218925]], dtype=float32)>, <tf.T


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.007367  , -0.00249147],
       [-0.00694738, -0.03978205]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00599784, -0.01861275],
       [ 0.03930775,  0.00212006]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01636764],
       [ 0.04658395]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01377356, -0.04244687], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.0336212 , -0.01623356], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04026078], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00738227, -0.00249529],
       [-0.00695503, -0.03981256]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00600746, -0.01859148],
       [ 0.0393322 ,  0.00212149]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00747818, -0.00246286],
       [-0.00682586, -0.03877306]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00607218, -0.01850522],
       [ 0.03984209,  0.00206973]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01676454],
       [ 0.04701451]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01374962, -0.04141337], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03412368, -0.01622261], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.0411294], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00749347, -0.00246716],
       [-0.00683352, -0.03883457]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00608425, -0.01844725],
       [ 0.039865  ,  0.00207276]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, n


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.007597  , -0.00243998],
       [-0.00668147, -0.03739786]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00615945, -0.01845954],
       [ 0.04037081,  0.00199959]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01717087],
       [ 0.04752535]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01371578, -0.04002032], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03460206, -0.0163098 ], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04208067], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00760464, -0.00243807],
       [-0.00667004, -0.03733683]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00615619, -0.01847765],
       [ 0.04040203,  0.00199641]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00768907, -0.00241756],
       [-0.0066057 , -0.03642178]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00624294, -0.01834359],
       [ 0.0408497 ,  0.00195224]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01760522],
       [ 0.04796901]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.0137197 , -0.03902801], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.0350532 , -0.01626175], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04297642], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00770436, -0.00241995],
       [-0.00661717, -0.03648329]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00625662, -0.01828567],
       [ 0.04087329,  0.0019553 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00781928, -0.00240088],
       [-0.00650321, -0.03544569]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00632705, -0.01820387],
       [ 0.04129152,  0.00190191]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01802382],
       [ 0.04841783]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01373586, -0.03803516], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03544527, -0.01622392], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04385719], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00783457, -0.00239706],
       [-0.00646509, -0.03501654]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0063316 , -0.01828874],
       [ 0.04131208,  0.00187983]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00790374, -0.00237083],
       [-0.00638549, -0.03410149]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00640596, -0.01816969],
       [ 0.04164407,  0.00183513]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01837604],
       [ 0.04891152]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01369422, -0.0366681 ], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03580504, -0.0162908 ], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04479728], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00791903, -0.00237322],
       [-0.00639696, -0.034163  ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00641868, -0.01812699],
       [ 0.04166756,  0.00183826]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00804149, -0.00235844],
       [-0.00632869, -0.03327847]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00650061, -0.01800246],
       [ 0.04198916,  0.00179384]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01877098],
       [ 0.04933172]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01376376, -0.03583058], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03608136, -0.01619509], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04561105], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00805675, -0.00236034],
       [-0.00632869, -0.03318691]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00651287, -0.01800534],
       [ 0.04201123,  0.00179031]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00812589, -0.00232792],
       [-0.00624906, -0.03224087]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00657643, -0.01790931],
       [ 0.04225503,  0.00174097]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01915332],
       [ 0.04977758]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01376139, -0.03477229], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03632155, -0.01617041], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04645373], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0081488 , -0.00233173],
       [-0.00625289, -0.03227139]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00658874, -0.0178879 ],
       [ 0.04227769,  0.00174257]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00823303, -0.00229692],
       [-0.00621506, -0.03141451]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00666605, -0.01779737],
       [ 0.04244665,  0.00169923]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01946542],
       [ 0.05017808]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01382701, -0.03392846], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03647232, -0.01612952], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04720248], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00825595, -0.00230169],
       [-0.00622272, -0.03144598]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00668416, -0.01774542],
       [ 0.04243659,  0.0017009 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00829449, -0.00226641],
       [-0.00613156, -0.03048372]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00671677, -0.0177104 ],
       [ 0.04260791,  0.00165116]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01975708],
       [ 0.05056847]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01379757, -0.03298104], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03662388, -0.01611773], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04793868], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00830977, -0.0022707 ],
       [-0.00613158, -0.03045368]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00672666, -0.01768892],
       [ 0.04260105,  0.00164982]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00841686, -0.00225544],
       [-0.00609753, -0.02966022]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00680957, -0.01760678],
       [ 0.04270389,  0.00160957]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01999791],
       [ 0.05093837]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01387967, -0.03214061], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03666722, -0.01607643], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04859285], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00843212, -0.00225735],
       [-0.00610897, -0.02967548]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00682329, -0.0175884 ],
       [ 0.04269528,  0.00161044]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00847065, -0.00222683],
       [-0.00604069, -0.02888203]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00686337, -0.01749681],
       [ 0.04277262,  0.00157074]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02026968],
       [ 0.05129949]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01387087, -0.03134865], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03672551, -0.01601437], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04925349], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00848593, -0.00222921],
       [-0.00604452, -0.02883673]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00687905, -0.01747847],
       [ 0.04276332,  0.0015684 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00859299, -0.00221157],
       [-0.00601044, -0.02798176]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00695542, -0.01741867],
       [ 0.04275369,  0.00152409]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02050216],
       [ 0.05167219]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01395494, -0.03044199], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03666592, -0.01600611], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04986227], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.008593  , -0.00220776],
       [-0.00601045, -0.02801228]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00695152, -0.01740032],
       [ 0.04278642,  0.00152493]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00864675, -0.00218678],
       [-0.00597265, -0.0275259 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00700788, -0.01723864],
       [ 0.04276692,  0.0015016 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0207738],
       [ 0.0519838]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01396772, -0.02996656], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03665353, -0.01586121], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05043864], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00865438, -0.00218534],
       [-0.00598409, -0.0275569 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00701921, -0.01722065],
       [ 0.04272759,  0.00150228]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, nu


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00873861, -0.00216484],
       [-0.00592718, -0.0267334 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00707826, -0.01711168],
       [ 0.04266961,  0.00146165]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02101116],
       [ 0.05235298]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01401221, -0.02915761], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03654572, -0.0158001 ], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05104755], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00875388, -0.00216293],
       [-0.00593482, -0.02677917]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00709215, -0.01709063],
       [ 0.042659  ,  0.00146314]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00879231, -0.00211668],
       [-0.00590077, -0.0259223 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00713916, -0.01701155],
       [ 0.04254257,  0.00141772]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02123056],
       [ 0.0527222 ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01403604, -0.02829644], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03639986, -0.01575257], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05164185], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00880758, -0.00212097],
       [-0.00591222, -0.02595329]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00715492, -0.01699009],
       [ 0.04253374,  0.00141946]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00885368, -0.00208902],
       [-0.0058477 , -0.02514505]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00719161, -0.01688538],
       [ 0.04236459,  0.00137898]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02142319],
       [ 0.05307389]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01403886, -0.02750863], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03624479, -0.01567843], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05221773], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00886895, -0.00209093],
       [-0.00585534, -0.02519083]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0072056 , -0.01686395],
       [ 0.04235572,  0.00138073]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00892261, -0.00206327],
       [-0.00586704, -0.02481222]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00727634, -0.01667042],
       [ 0.04214498,  0.00136169]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0216788 ],
       [ 0.05338601]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01412868, -0.02714735], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03598496, -0.01548733], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05268768], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0089379 , -0.00206327],
       [-0.00585181, -0.02450514]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00728613, -0.01671048],
       [ 0.04210332,  0.00134621]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0090297 , -0.00204086],
       [-0.00581773, -0.02401924]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00734418, -0.01654864],
       [ 0.04186096,  0.00132032]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0218543 ],
       [ 0.05372692]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01418548, -0.02634124], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03569663, -0.01542067], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05316187], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00902207, -0.00203705],
       [-0.00581773, -0.02397346]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00734507, -0.01654257],
       [ 0.04186171,  0.00131843]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00905284, -0.0020051 ],
       [-0.00580653, -0.02331781]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00739391, -0.01642285],
       [ 0.04160029,  0.00128524]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02199461],
       [ 0.05404949]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.0141947, -0.0256224], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03541548, -0.01533912], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05363614], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00908336, -0.00200939],
       [-0.00581035, -0.02328777]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00741332, -0.0164168 ],
       [ 0.04155706,  0.00128333]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, n


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0090989 , -0.00197601],
       [-0.00579537, -0.0229702 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00745391, -0.01621794],
       [ 0.04127219,  0.00126736]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0221965 ],
       [ 0.05432216]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01423105, -0.02524062], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03508094, -0.01516073], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05399586], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00912179, -0.00197983],
       [-0.00579537, -0.02292442]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.007465  , -0.01621189],
       [ 0.04126334,  0.00126542]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00916021, -0.00194836],
       [-0.00574987, -0.02220821]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00750458, -0.01609674],
       [ 0.04088046,  0.00122886]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0223078 ],
       [ 0.05465065]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01424312, -0.02445804], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03470305, -0.01509036], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05443703], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00915259, -0.00194263],
       [-0.00574607, -0.02222347]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00749879, -0.01607869],
       [ 0.04088349,  0.0012296 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00916807, -0.00189352],
       [-0.00572722, -0.02148962]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00753193, -0.01597377],
       [ 0.04049948,  0.00119027]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0223789 ],
       [ 0.05495555]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01422699, -0.02369612], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03435064, -0.01501475], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05485223], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00918334, -0.00189734],
       [-0.00573867, -0.02152014]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0075462 , -0.01595229],
       [ 0.04049036,  0.00119209]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0092141 , -0.00186777],
       [-0.00571221, -0.02115679]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00759152, -0.01577287],
       [ 0.04007997,  0.00117386]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02252952],
       [ 0.05521433]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01426625, -0.02334472], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03391219, -0.01482821], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05514552], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00922937, -0.00186825],
       [-0.00571603, -0.02111149]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00760291, -0.01575162],
       [ 0.0400103 ,  0.0011718 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00926009, -0.00183678],
       [-0.00571623, -0.02054787]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00765297, -0.01562393],
       [ 0.03959277,  0.00114221]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02262694],
       [ 0.05549438]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01431115, -0.02270548], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.0334192 , -0.01471538], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.0554336], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00925248, -0.00183105],
       [-0.00570863, -0.02051735]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0076471 , -0.01561483],
       [ 0.03956675,  0.001141  ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00927561, -0.00179815],
       [-0.00567835, -0.02009344]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00767628, -0.01543045],
       [ 0.03910353,  0.00111901]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02271829],
       [ 0.05575013]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01429059, -0.02222538], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03296002, -0.01455588], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.0557136], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00926035, -0.00179434],
       [-0.00568598, -0.0201087 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00767734, -0.01541206],
       [ 0.03907458,  0.00111993]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00928347, -0.00176334],
       [-0.00565569, -0.01951504]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00771553, -0.01527019],
       [ 0.03860175,  0.00108899]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02278079],
       [ 0.0560047 ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01428198, -0.0216109 ], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03246836, -0.01443407], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.0559644], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0092911 , -0.00176191],
       [-0.0056557 , -0.019485  ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00772345, -0.01526141],
       [ 0.03856356,  0.00108756]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00927603, -0.00172853],
       [-0.00564444, -0.01916742]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00773084, -0.01508485],
       [ 0.0381218 ,  0.00107196]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02282753],
       [ 0.05621915]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01426092, -0.02123594], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03202229, -0.01427509], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05618175], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0092913 , -0.00172663],
       [-0.00564826, -0.01913691]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00774225, -0.01507607],
       [ 0.03808032,  0.00107049]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00932961, -0.00170231],
       [-0.00560647, -0.01855755]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00777072, -0.01498628],
       [ 0.03761454,  0.00104072]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02283943],
       [ 0.05643912]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01428434, -0.02060749], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03153467, -0.01420465], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05635632], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00928387, -0.00169468],
       [-0.00561413, -0.01857281]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.007763  , -0.01496789],
       [ 0.03759211,  0.00104164]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00932215, -0.00166702],
       [-0.00561808, -0.01823997]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00780374, -0.01481586],
       [ 0.03712617,  0.00102318]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02288559],
       [ 0.05661875]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01428431, -0.02025399], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03106244, -0.01405932], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05647667], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00933742, -0.00166893],
       [-0.00561809, -0.01820946]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00781522, -0.0148068 ],
       [ 0.037117  ,  0.00102183]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00931473, -0.00162411],
       [-0.00558777, -0.01790524]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00782701, -0.01464801],
       [ 0.03662229,  0.00100641]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0229068 ],
       [ 0.05680304]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01425439, -0.01989098], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03057358, -0.01390436], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05660731], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00932237, -0.00162411],
       [-0.00559159, -0.01793575]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00783295, -0.01462959],
       [ 0.03661711,  0.00100739]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0093073 , -0.00159264],
       [-0.00555745, -0.01734161]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00784938, -0.01452203],
       [ 0.0361014 ,  0.00097761]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0228978 ],
       [ 0.05699728]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.0142224 , -0.01930409], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.03006426, -0.01380884], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05673166], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00929968, -0.00158548],
       [-0.00554983, -0.01735735]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00783477, -0.01450547],
       [ 0.03607845,  0.00097798]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00927695, -0.00155401],
       [-0.00554236, -0.01705503]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00784886, -0.01434028],
       [ 0.03556947,  0.00096282]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02291732],
       [ 0.05716023]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.0141775 , -0.01896878], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02956459, -0.01364525], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05681236], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00929221, -0.0015564 ],
       [-0.00554999, -0.01705551]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00786239, -0.01432341],
       [ 0.03553058,  0.00096333]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00927714, -0.00152111],
       [-0.0055311 , -0.01672268]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788471, -0.01415152],
       [ 0.03498385,  0.00094521]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0229453 ],
       [ 0.05731506]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01416923, -0.01860961], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02899281, -0.01347227], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05682794], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00920852, -0.00151014],
       [-0.00552352, -0.01672316]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00785035, -0.01413468],
       [ 0.03497954,  0.00094567]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00923155, -0.00148296],
       [-0.00547407, -0.01616001]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00786158, -0.0140186 ],
       [ 0.03445752,  0.00091677]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02288267],
       [ 0.05748618]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01407185, -0.01802256], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02852775, -0.01338037], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05694475], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00917818, -0.00147533],
       [-0.00547792, -0.01619053]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00784996, -0.01400014],
       [ 0.03443846,  0.00091775]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00917832, -0.00144625],
       [-0.00548569, -0.01591921]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788786, -0.01382964],
       [ 0.03385163,  0.00090409]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02290692],
       [ 0.05761304]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01403965, -0.01773534], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02795567, -0.01319495], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.0569078], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00915544, -0.00143909],
       [-0.00548189, -0.01593494]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00787097, -0.01381121],
       [ 0.03383652,  0.00090508]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00914036, -0.00141239],
       [-0.00545155, -0.01564884]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788293, -0.01362345],
       [ 0.03329423,  0.0008909 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02289162],
       [ 0.057739  ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01396995, -0.01743175], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02743201, -0.01301589], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05690525], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00913273, -0.00140715],
       [-0.00545536, -0.01566458]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788404, -0.01360528],
       [ 0.0332328 ,  0.00089177]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00910239, -0.00137329],
       [-0.00541739, -0.01533127]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788134, -0.01345969],
       [ 0.03270245,  0.00087413]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02286491],
       [ 0.05786166]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01390547, -0.01707908], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02688816, -0.01285744], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05687958], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00909476, -0.00136805],
       [-0.00540976, -0.01511621]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00787598, -0.0134885 ],
       [ 0.03267092,  0.00086248]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00906437, -0.00133085],
       [-0.00540226, -0.01481962]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788024, -0.01333282],
       [ 0.03212843,  0.00084752]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02280851],
       [ 0.05798147]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01384863, -0.01654021], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02638453, -0.01275998], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05686212], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.009072  , -0.00132847],
       [-0.00540608, -0.01484299]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788848, -0.01331461],
       [ 0.03209067,  0.00084845]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0090035 , -0.00129271],
       [-0.00536809, -0.01456404]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00786794, -0.01315487],
       [ 0.03154436,  0.00083491]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02277984],
       [ 0.05807876]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01376698, -0.01624809], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02584621, -0.01259271], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05678956], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00901876, -0.00129414],
       [-0.00537954, -0.0145874 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788497, -0.01312115],
       [ 0.03150425,  0.00083599]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00896548, -0.0012641 ],
       [-0.00537585, -0.01432371]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00788329, -0.0129691 ],
       [ 0.03100825,  0.00082277]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02275676],
       [ 0.05815334]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01373305, -0.01597531], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02533756, -0.01243022], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05668025], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00897314, -0.00126171],
       [-0.00533773, -0.01431656]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00786911, -0.01295106],
       [ 0.03097962,  0.00082267]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00888934, -0.00122356],
       [-0.00532641, -0.01407528]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00784903, -0.01280392],
       [ 0.03049931,  0.00080936]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02270833],
       [ 0.05823009]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01361861, -0.01568992], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02487589, -0.01227873], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05661298], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0089046 , -0.00122452],
       [-0.00532642, -0.01400661]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00785982, -0.01280893],
       [ 0.03045969,  0.00080601]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00885134, -0.00119543],
       [-0.00530749, -0.01383448]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00785852, -0.01263055],
       [ 0.02993353,  0.00079737]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02267446],
       [ 0.05829072]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01356494, -0.0154196 ], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02434793, -0.01211476], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05646747], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00885897, -0.00119305],
       [-0.00530749, -0.01377392]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00786379, -0.01262658],
       [ 0.02986486,  0.00079439]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0088133 , -0.0011673 ],
       [-0.00528852, -0.01356316]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00785326, -0.01248344],
       [ 0.02940557,  0.00078411]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02264235],
       [ 0.05834261]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01350931, -0.01512659], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02388069, -0.01198022], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05633135], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00879806, -0.00115967],
       [-0.00527328, -0.01336288]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00783547, -0.01251568],
       [ 0.02938059,  0.00077309]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00873716, -0.00112915],
       [-0.00524671, -0.01312256]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00782703, -0.01234865],
       [ 0.02885737,  0.00076114]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02255026],
       [ 0.05841347]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01339764, -0.01465094], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02339175, -0.01186853], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05623075], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00874479, -0.0011301 ],
       [-0.00525053, -0.01313782]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00783215, -0.01233941],
       [ 0.02885295,  0.00076168]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00867625, -0.00109673],
       [-0.00521632, -0.0128355 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00781204, -0.01220686],
       [ 0.02836663,  0.00074566]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02248882],
       [ 0.05845568]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01330873, -0.01433036], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02293161, -0.01174177], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05608679], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00866101, -0.00109339],
       [-0.00519727, -0.01283598]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00779086, -0.01219026],
       [ 0.02835036,  0.00074569]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00860771, -0.00106716],
       [-0.00519355, -0.01265621]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00779297, -0.012035  ],
       [ 0.02785359,  0.0007369 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02243589],
       [ 0.05848514]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01322849, -0.01412363], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02247772, -0.01158169], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05592299], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00861534, -0.00106668],
       [-0.00519356, -0.01260328]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00779817, -0.01202925],
       [ 0.02781727,  0.00073445]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0084858 , -0.00102997],
       [-0.00515557, -0.01242352]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00774748, -0.01187275],
       [ 0.0273572 ,  0.0007255 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02235884],
       [ 0.05851136]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01307038, -0.01385522], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.0220391, -0.0114264], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05577132], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00847054, -0.00102425],
       [-0.00515939, -0.01237774]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00774244, -0.01186725],
       [ 0.02732805,  0.00072286]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, n


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00841726, -0.00098944],
       [-0.00511373, -0.01218843]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00771976, -0.01171054],
       [ 0.02680265,  0.00071326]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02230373],
       [ 0.05852344]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01296506, -0.01358138], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02157304, -0.01128085], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05556687], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00842489, -0.00098991],
       [-0.00512136, -0.0122118 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00772817, -0.01169204],
       [ 0.02679712,  0.00071437]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00833344, -0.0009582 ],
       [-0.00510621, -0.01198649]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00770218, -0.01154495],
       [ 0.02629099,  0.00070316]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02223499],
       [ 0.05853166]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.0128784 , -0.01334384], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02111553, -0.01112417], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05536017], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00834107, -0.00095749],
       [-0.00511003, -0.01199436]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00771064, -0.0115357 ],
       [ 0.02625507,  0.00070371]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00827252, -0.00092888],
       [-0.00507199, -0.01171494]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00768684, -0.01140659],
       [ 0.02583198,  0.00068844]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02217118],
       [ 0.05853471]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01278825, -0.01304161], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.02067611, -0.01100326], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05514526], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00828779, -0.00093031],
       [-0.00507581, -0.01172304]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00769806, -0.01138968],
       [ 0.02579369,  0.00068901]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0081811 , -0.00089717],
       [-0.0050149 , -0.01153541]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00763033, -0.01125533],
       [ 0.0253721 ,  0.00067955]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0220884 ],
       [ 0.05853082]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01264026, -0.01283018], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.0203068, -0.0108612], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05497344], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0081811 , -0.00089836],
       [-0.0050149 , -0.01148224]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0076356 , -0.01124963],
       [ 0.02535092,  0.00067694]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, n

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00811252, -0.0008719 ],
       [-0.00501117, -0.01132512]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0076265 , -0.01111288],
       [ 0.02490893,  0.000669  ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02203612],
       [ 0.05851454]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01257766, -0.01259413], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01987083, -0.01072746], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05472026], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00812016, -0.00087237],
       [-0.00501118, -0.01133323]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00763379, -0.01109597],
       [ 0.02485886,  0.00066958]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00802109, -0.00084114],
       [-0.00496934, -0.01110744]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00758244, -0.01096173],
       [ 0.02444242,  0.00065829]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.021944 ],
       [ 0.0584976]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01244229, -0.01234739], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01947628, -0.0105881 ], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05450666], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00802109, -0.00084066],
       [-0.00496934, -0.01111555]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0075878 , -0.01094482],
       [ 0.02440752,  0.00065889]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, n


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00796016, -0.0008173 ],
       [-0.00491985, -0.01089001]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00755944, -0.01080953],
       [ 0.02397055,  0.0006475 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02188518],
       [ 0.05846398]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01234566, -0.01210559], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.0190505 , -0.01044732], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05423198], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0079678 , -0.00081468],
       [-0.00492748, -0.01085973]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00756999, -0.01080094],
       [ 0.02391936,  0.0006452 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00786108, -0.0007844 ],
       [-0.0049085 , -0.01071787]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00752394, -0.01066113],
       [ 0.02350374,  0.00063802]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02180651],
       [ 0.05843112]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01223237, -0.01189841], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01864658, -0.01030511], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05397754], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0078611 , -0.00078392],
       [-0.00488182, -0.01065731]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00751621, -0.0106544 ],
       [ 0.02347285,  0.0006353 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00779633, -0.00075984],
       [-0.00487427, -0.01051593]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00750837, -0.010507  ],
       [ 0.02304629,  0.00062806]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02175559],
       [ 0.05838277]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01214086, -0.0116732 ], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01822038, -0.0101643 ], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05367097], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0077849 , -0.00075674],
       [-0.00486284, -0.01051569]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00749313, -0.010507  ],
       [ 0.02302725,  0.00062806]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00770489, -0.00073314],
       [-0.00480953, -0.01028991]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00744709, -0.01038574],
       [ 0.02264816,  0.00061678]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02164785],
       [ 0.05834848]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01198987, -0.01142085], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01790118, -0.01005124], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05346933], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0077087 , -0.00073266],
       [-0.00481716, -0.01029801]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00745581, -0.01036883],
       [ 0.02261211,  0.00061738]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00761343, -0.0007062 ],
       [-0.00477911, -0.01014853]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00741396, -0.0102358 ],
       [ 0.02220453,  0.00060991]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0215909 ],
       [ 0.05828514]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01187401, -0.01125499], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01751984, -0.0099061 ], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05316732], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.007602  , -0.00070381],
       [-0.00476768, -0.0100956 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00740057, -0.01023021],
       [ 0.0221841 ,  0.00060709]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00752578, -0.00067949],
       [-0.00475631, -0.00990725]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00737721, -0.01012166],
       [ 0.02181374,  0.00059666]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02149304],
       [ 0.05824205]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.0117631 , -0.01098209], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01717474, -0.00980112], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.0529268], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0075296 , -0.00067997],
       [-0.00476013, -0.00991535]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00738783, -0.01010474],
       [ 0.02177766,  0.00059726]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00743814, -0.00065684],
       [-0.00471826, -0.00975776]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00733954, -0.00999641],
       [ 0.02144959,  0.00058899]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02142454],
       [ 0.0581829 ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01164341, -0.01080706], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01687155, -0.00968345], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05267742], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00744577, -0.00065613],
       [-0.00471826, -0.00969696]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00734695, -0.00999846],
       [ 0.02141316,  0.00058611]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00735429, -0.00063467],
       [-0.00469926, -0.00954676]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00731339, -0.00988933],
       [ 0.02109368,  0.0005784 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02135263],
       [ 0.05812497]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01154901, -0.0105772 ], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01655386, -0.00958259], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05241885], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.0073581 , -0.00063515],
       [-0.00470307, -0.00956249]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00731584, -0.00987159],
       [ 0.02107562,  0.0005793 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00730095, -0.0006063 ],
       [-0.00466118, -0.00939536]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00728236, -0.0097719 ],
       [ 0.02074681,  0.0005703 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02128387],
       [ 0.05806001]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01145882, -0.01039906], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01624716, -0.00947511], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05215423], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00727045, -0.00060391],
       [-0.00464975, -0.00940347]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00726328, -0.00975485],
       [ 0.02072684,  0.00057062]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00721712, -0.00058532],
       [-0.00460405, -0.0091846 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00722612, -0.00966309],
       [ 0.02040639,  0.00055949]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02119821],
       [ 0.05799418]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01131965, -0.01016499], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01598069, -0.00937678], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05191945], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00722093, -0.00058556],
       [-0.00460786, -0.00919247]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00723684, -0.00965381],
       [ 0.02037023,  0.00056009]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, 


 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00712183, -0.00056124],
       [-0.00458506, -0.00905848]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00719036, -0.00952647],
       [ 0.02001629,  0.0005532 ]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02111745],
       [ 0.05791122]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.01121024, -0.01001281], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01564633, -0.00924413], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05161303], dtype=float32)>]

 gradients :  [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00712565, -0.00056052],
       [-0.00458506, -0.00901294]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00719289, -0.0095261 ],
       [ 0.01998158,  0.00055111]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32,

In [70]:
# 최종 예측값 출력
print("\n최종 예측값:\n", y_pred.numpy())


최종 예측값:
 [[0.35330665]
 [0.8003734 ]
 [0.8007425 ]
 [0.25127497]]
