In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import os
import sys

2024-07-15 16:27:29.711749: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-15 16:27:29.810468: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-15 16:27:31.606019: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


## 파라메트릭 Tanh

In [22]:
class abTanh(layers.Layer):
    def __init__(self, units=None, init_a=7, init_b=0, **kwargs):
        super(abTanh, self).__init__(**kwargs)
        self.units = units
        self.init_a = init_a
        self.init_b = init_b

    def build(self, input_shape):
        units_shape = self.units if self.units else input_shape[1:]
        
        self.b = self.add_weight(shape=units_shape, initializer=tf.constant_initializer(self.init_b), trainable=True, name="b")
        self.a = self.add_weight(shape=units_shape, initializer=tf.constant_initializer(self.init_a), trainable=True, name="a")

    def call(self, inputs, **kwargs):
        x = tf.subtract(inputs, self.b)
        x = tf.nn.tanh(x)
        x = tf.multiply(x, self.a)
        return x

In [23]:
from tensorflow.keras import layers, models, optimizers

## XOR 문제

In [24]:
# 데이터 준비
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [25]:
# 모델 구성
model = models.Sequential()
model.add(layers.Input(shape=(2,)))
model.add(layers.Dense(10))
model.add(abTanh(units=10))
model.add(layers.Dense(1, activation='sigmoid'))

In [26]:
# 모델 컴파일
model.compile(optimizer=optimizers.Adam(), loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
# 모델 훈련
model.fit(X, y, epochs=1000, verbose=2)

Epoch 1/1000
1/1 - 2s - loss: 1.0377 - accuracy: 0.7500 - 2s/epoch - 2s/step
Epoch 2/1000
1/1 - 0s - loss: 1.0113 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 3/1000
1/1 - 0s - loss: 0.9864 - accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 4/1000
1/1 - 0s - loss: 0.9629 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 5/1000
1/1 - 0s - loss: 0.9409 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 6/1000
1/1 - 0s - loss: 0.9203 - accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 7/1000
1/1 - 0s - loss: 0.9014 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 8/1000
1/1 - 0s - loss: 0.8843 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 9/1000
1/1 - 0s - loss: 0.8690 - accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 10/1000
1/1 - 0s - loss: 0.8554 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 11/1000
1/1 - 0s - loss: 0.8438 - accuracy: 0.5000 - 9ms/epoch - 9ms/step
Epoch 12/1000
1/1 - 0s - loss: 0.8336 - accuracy: 0.5000 - 9ms/epoch - 9ms/step
Epoch 13/1000
1/1 - 0s - loss: 0.8253 - accur

Epoch 104/1000
1/1 - 0s - loss: 0.6576 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 105/1000
1/1 - 0s - loss: 0.6563 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 106/1000
1/1 - 0s - loss: 0.6551 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 107/1000
1/1 - 0s - loss: 0.6538 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 108/1000
1/1 - 0s - loss: 0.6525 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 109/1000
1/1 - 0s - loss: 0.6513 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 110/1000
1/1 - 0s - loss: 0.6500 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 111/1000
1/1 - 0s - loss: 0.6488 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 112/1000
1/1 - 0s - loss: 0.6475 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 113/1000
1/1 - 0s - loss: 0.6463 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 114/1000
1/1 - 0s - loss: 0.6449 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 115/1000
1/1 - 0s - loss: 0.6437 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 116/1000
1/1 - 0s - lo

1/1 - 0s - loss: 0.5327 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 206/1000
1/1 - 0s - loss: 0.5315 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 207/1000
1/1 - 0s - loss: 0.5303 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 208/1000
1/1 - 0s - loss: 0.5291 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 209/1000
1/1 - 0s - loss: 0.5278 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 210/1000
1/1 - 0s - loss: 0.5265 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 211/1000
1/1 - 0s - loss: 0.5253 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 212/1000
1/1 - 0s - loss: 0.5241 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 213/1000
1/1 - 0s - loss: 0.5230 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 214/1000
1/1 - 0s - loss: 0.5217 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 215/1000
1/1 - 0s - loss: 0.5205 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 216/1000
1/1 - 0s - loss: 0.5193 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 217/1000
1/1 - 0s - loss: 0.5181 - ac

Epoch 307/1000
1/1 - 0s - loss: 0.4077 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 308/1000
1/1 - 0s - loss: 0.4065 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 309/1000
1/1 - 0s - loss: 0.4052 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 310/1000
1/1 - 0s - loss: 0.4041 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 311/1000
1/1 - 0s - loss: 0.4028 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 312/1000
1/1 - 0s - loss: 0.4016 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 313/1000
1/1 - 0s - loss: 0.4004 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 314/1000
1/1 - 0s - loss: 0.3991 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 315/1000
1/1 - 0s - loss: 0.3979 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 316/1000
1/1 - 0s - loss: 0.3966 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 317/1000
1/1 - 0s - loss: 0.3954 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 318/1000
1/1 - 0s - loss: 0.3942 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 319/1000
1/1 - 0s - lo

Epoch 408/1000
1/1 - 0s - loss: 0.2830 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 409/1000
1/1 - 0s - loss: 0.2819 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 410/1000
1/1 - 0s - loss: 0.2807 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 411/1000
1/1 - 0s - loss: 0.2794 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 412/1000
1/1 - 0s - loss: 0.2782 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 413/1000
1/1 - 0s - loss: 0.2772 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 414/1000
1/1 - 0s - loss: 0.2759 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 415/1000
1/1 - 0s - loss: 0.2748 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 416/1000
1/1 - 0s - loss: 0.2736 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 417/1000
1/1 - 0s - loss: 0.2724 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 418/1000
1/1 - 0s - loss: 0.2712 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 419/1000
1/1 - 0s - loss: 0.2701 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 420/1000
1/1 - 0s - lo

1/1 - 0s - loss: 0.1763 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 510/1000
1/1 - 0s - loss: 0.1754 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 511/1000
1/1 - 0s - loss: 0.1745 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 512/1000
1/1 - 0s - loss: 0.1736 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 513/1000
1/1 - 0s - loss: 0.1728 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 514/1000
1/1 - 0s - loss: 0.1719 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 515/1000
1/1 - 0s - loss: 0.1710 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 516/1000
1/1 - 0s - loss: 0.1702 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 517/1000
1/1 - 0s - loss: 0.1693 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 518/1000
1/1 - 0s - loss: 0.1685 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 519/1000
1/1 - 0s - loss: 0.1676 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 520/1000
1/1 - 0s - loss: 0.1668 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 521/1000
1/1 - 0s - loss: 0.1660 - ac

Epoch 610/1000
1/1 - 0s - loss: 0.1053 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 611/1000
1/1 - 0s - loss: 0.1048 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 612/1000
1/1 - 0s - loss: 0.1043 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 613/1000
1/1 - 0s - loss: 0.1038 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 614/1000
1/1 - 0s - loss: 0.1033 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 615/1000
1/1 - 0s - loss: 0.1027 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 616/1000
1/1 - 0s - loss: 0.1022 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 617/1000
1/1 - 0s - loss: 0.1017 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 618/1000
1/1 - 0s - loss: 0.1012 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 619/1000
1/1 - 0s - loss: 0.1007 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 620/1000
1/1 - 0s - loss: 0.1002 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 621/1000
1/1 - 0s - loss: 0.0997 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 622/1000
1/1 - 0s - lo

Epoch 711/1000
1/1 - 0s - loss: 0.0648 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 712/1000
1/1 - 0s - loss: 0.0645 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 713/1000
1/1 - 0s - loss: 0.0642 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 714/1000
1/1 - 0s - loss: 0.0639 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 715/1000
1/1 - 0s - loss: 0.0636 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 716/1000
1/1 - 0s - loss: 0.0633 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 717/1000
1/1 - 0s - loss: 0.0630 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 718/1000
1/1 - 0s - loss: 0.0628 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 719/1000
1/1 - 0s - loss: 0.0625 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 720/1000
1/1 - 0s - loss: 0.0622 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 721/1000
1/1 - 0s - loss: 0.0619 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 722/1000
1/1 - 0s - loss: 0.0616 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 723/1000
1/1 - 0s - lo

Epoch 812/1000
1/1 - 0s - loss: 0.0422 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 813/1000
1/1 - 0s - loss: 0.0420 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 814/1000
1/1 - 0s - loss: 0.0418 - accuracy: 1.0000 - 10ms/epoch - 10ms/step
Epoch 815/1000
1/1 - 0s - loss: 0.0417 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 816/1000
1/1 - 0s - loss: 0.0415 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 817/1000
1/1 - 0s - loss: 0.0413 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 818/1000
1/1 - 0s - loss: 0.0412 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 819/1000
1/1 - 0s - loss: 0.0410 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 820/1000
1/1 - 0s - loss: 0.0409 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 821/1000
1/1 - 0s - loss: 0.0407 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 822/1000
1/1 - 0s - loss: 0.0405 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 823/1000
1/1 - 0s - loss: 0.0404 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 824/1000
1/1 - 0s - 

Epoch 913/1000
1/1 - 0s - loss: 0.0290 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 914/1000
1/1 - 0s - loss: 0.0289 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 915/1000
1/1 - 0s - loss: 0.0288 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 916/1000
1/1 - 0s - loss: 0.0288 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 917/1000
1/1 - 0s - loss: 0.0287 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 918/1000
1/1 - 0s - loss: 0.0286 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 919/1000
1/1 - 0s - loss: 0.0284 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 920/1000
1/1 - 0s - loss: 0.0284 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 921/1000
1/1 - 0s - loss: 0.0283 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 922/1000
1/1 - 0s - loss: 0.0282 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 923/1000
1/1 - 0s - loss: 0.0281 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 924/1000
1/1 - 0s - loss: 0.0280 - accuracy: 1.0000 - 9ms/epoch - 9ms/step
Epoch 925/1000
1/1 - 0s - lo

In [28]:
# 예측 결과 확인
predictions = model.predict(X)
print("Predictions:")
print(predictions)

1/1 [==============================] - 0s 143ms/step
Predictions:
[[0.01787191]
 [0.97530895]
 [0.9801437 ]
 [0.0239225 ]]


- 1번째 선형변환 가중치 W, b

In [29]:
print(model.layers[0].weights)

[<tf.Variable 'dense_4/kernel:0' shape=(2, 10) dtype=float32, numpy=
array([[-0.62924343,  0.9249539 , -0.95594364, -0.64475614, -1.1123688 ,
         0.61830384,  0.9482329 ,  0.15580946,  0.04771351, -0.12433067],
       [-0.59574395, -0.17046893,  1.1945268 , -0.4391057 , -0.99374396,
        -1.0495126 , -0.76061237,  0.10422631,  0.02445871,  0.66797924]],
      dtype=float32)>, <tf.Variable 'dense_4/bias:0' shape=(10,) dtype=float32, numpy=
array([-0.13601865, -0.07104834,  0.36503273,  0.47418755,  0.00916714,
       -0.2467294 ,  0.27376485,  0.03496342,  0.02680997, -0.0031633 ],
      dtype=float32)>]


- 1번째 비선형변환 abTanh의 a와 b 값

In [30]:
print(model.layers[1].weights)

[<tf.Variable 'ab_tanh_2/b:0' shape=(10,) dtype=float32, numpy=
array([ 0.13601865,  0.07104834, -0.36503273, -0.47418755, -0.00916714,
        0.2467294 , -0.27376485, -0.03496342, -0.02680997,  0.0031633 ],
      dtype=float32)>, <tf.Variable 'ab_tanh_2/a:0' shape=(10,) dtype=float32, numpy=
array([7.078324 , 7.315827 , 8.133766 , 7.3671565, 7.5511374, 7.550572 ,
       7.573554 , 6.849881 , 6.9141355, 7.1614842], dtype=float32)>]


- 마지막 출력층 선형변환 가중치

In [31]:
print(model.layers[2].weights)

[<tf.Variable 'dense_5/kernel:0' shape=(10, 1) dtype=float32, numpy=
array([[-0.6726824 ],
       [-0.8209469 ],
       [-0.63043725],
       [ 0.42913258],
       [-1.1662788 ],
       [ 0.48973346],
       [-0.9456808 ],
       [ 0.53748214],
       [-0.2602351 ],
       [-0.78335047]], dtype=float32)>, <tf.Variable 'dense_5/bias:0' shape=(1,) dtype=float32, numpy=array([-0.03321759], dtype=float32)>]
